### Import taxcalc package and pandas

In [1]:
from taxcalc import *
import pandas as pd

### Create baseline calculator from new policy and records class object

In [2]:
policy_x = Policy()
recs_x = Records()
calc_x = Calculator(policy=policy_x, records=recs_x)

You loaded data for 2009.
Your data have been extrapolated to 2013.

taxcalc/behavior.py:189: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = values[year]

### Create reform calculator

In [5]:
policy_y = Policy()
# Create reform dictionary
reform = {
    2016: {
        '_CTC_new_rt': [1],
        '_CTC_new_c': [2000],
        '_CTC_new_prt': [0.05],
        '_CTC_new_ps': [[75000, 110000, 55000, 75000, 75000, 55000]]
    }
}
# Implement reform
policy_y.implement_reform(reform)
recs_y = Records()
calc_y = Calculator(policy=policy_y, records=recs_y)

You loaded data for 2009.
Your data have been extrapolated to 2013.

### Advance to 2016 and run the calculators

In [6]:
calc_x.advance_to_year(2016)
calc_x.calc_all()
calc_y.advance_to_year(2016)
calc_y.calc_all()

### Create and export differences table

In [21]:
diffs_table = utils.create_difference_table(recs_x, recs_y, groupby='small_income_bins')
diffs_table.to_csv('diffs_table.csv')
diffs_table

,tax_cut,tax_inc,count,mean,tot_change,perc_inc,perc_cut,share_of_change
0,"3,186",0,"4,808,205",-1,"-5,029,466",0.00%,0.07%,0.00%
1,"1,070,622",0,"11,911,979",-193,"-2,294,548,719",0.00%,8.99%,1.94%
2,"1,777,885",0,"11,555,281",-461,"-5,328,373,942",0.00%,15.39%,4.51%
3,"2,821,397",0,"12,181,161",-670,"-8,159,833,826",0.00%,23.16%,6.91%
4,"3,795,038",0,"12,771,576",-990,"-12,646,115,663",0.00%,29.71%,10.71%
5,"2,586,238",0,"10,157,676",-832,"-8,450,628,947",0.00%,25.46%,7.16%
6,"2,532,788",0,"9,331,870",-914,"-8,533,945,871",0.00%,27.14%,7.23%
7,"4,160,383",0,"16,502,465",-835,"-13,787,626,322",0.00%,25.21%,11.68%
8,"3,107,202",0,"13,353,749",-774,"-10,336,335,143",0.00%,23.27%,8.75%
9,"5,404,219",0,"23,276,669",-767,"-17,848,504,131",0.00%,23.22%,15.11%
10,"3,518,050",0,"13,493,219",-859,"-11,588,226,768",0.00%,26.07%,9.81%
11,"7,227,790",0,"22,406,259",-842,"-18,873,385,123",0.00%,32.26%,15.98%
12,"203,502",0,"6,849,921",-34,"-236,311,359",0.00%,2.97%,0.20%
13,604,0,"999,610",-1,"-1,387,688",0.00%,0.06%,0.00%
14,50,0,"235,236",-1,"-171,680",0.00%,0.02%,0.00%
15,48,0,"95,339",-1,"-138,290",0.00%,0.05%,0.00%
16,70,0,"130,040",-2,"-215,429",0.00%,0.05%,0.00%
17,10,0,"32,594",-1,"-19,607",0.00%,0.03%,0.00%
18,0,0,"17,145",0,0,0.00%,0.00%,-0.00%
sums,"38,209,080",0,"170,109,995",n/a,"-118,090,797,973",n/a,n/a,100.00%

### Create and export one-year diagnostic table

In [22]:
diagnotic_table = utils.create_diagnostic_table(calc_y)
diagnotic_table.to_csv('diagnostic_table.csv')
diagnotic_table

                                   2016
Returns (#m)                      170.1
AGI ($b)                       10,507.8
Itemizers (#m)                     45.1
Itemized Deduction ($b)         1,303.6
Standard Deduction Filers (#m)    111.9
Standard Deduction ($b)           992.0
Personal Exemption ($b)         1,191.4
Taxable Income ($b)             7,493.1
Regular Tax ($b)                1,642.2
AMT Income ($b)                 9,824.1
AMT Liability ($b)                 40.1
AMT Filers (#m)                     5.0
Tax before Credits ($b)         1,563.1
Refundable Credits ($b)           218.8
Nonrefundable Credits ($b)         72.7
Reform Surtaxes ($b)                0.0
Ind Income Tax ($b)             1,305.3
Payroll Taxes ($b)              1,045.3
Combined Liability ($b)         2,350.6

### Create and export 10-year diagnostic table

In [23]:
ten_year_table = utils.multiyear_diagnostic_table(calc_y, 10)
ten_year_table.to_csv('ten_year_table.csv')
ten_year_table

,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
Returns (#m),170.1,172.4,174.1,175.6,177.1,178.4,179.8,181.0,182.3,183.6
AGI ($b),"10,507.8","10,960.8","11,406.5","11,828.8","12,284.2","12,786.1","13,327.2","13,900.3","14,505.9","15,142.5"
Itemizers (#m),45.1,45.8,46.3,46.8,47.4,47.9,48.4,48.9,49.5,50.0
Itemized Deduction ($b),"1,303.6","1,365.6","1,440.5","1,515.7","1,595.4","1,677.4","1,765.6","1,856.1","1,949.6","2,045.8"
Standard Deduction Filers (#m),111.9,113.3,114.1,114.8,115.5,116.0,116.5,116.9,117.4,117.9
Standard Deduction ($b),992.0,"1,019.1","1,051.6","1,083.5","1,117.4","1,151.4","1,187.2","1,221.6","1,258.2","1,296.5"
Personal Exemption ($b),"1,191.4","1,218.1","1,254.5","1,290.8","1,329.3","1,368.1","1,408.6","1,449.6","1,491.3","1,534.5"
Taxable Income ($b),"7,493.1","7,836.7","8,149.5","8,440.1","8,752.5","9,112.1","9,503.3","9,922.3","10,369.2","10,842.0"
Regular Tax ($b),"1,642.2","1,718.6","1,784.0","1,842.9","1,908.6","1,986.7","2,072.6","2,166.4","2,267.2","2,375.0"
AMT Income ($b),"9,824.1","10,242.9","10,646.3","11,026.0","11,436.4","11,891.5","12,382.8","12,905.0","13,457.3","14,038.6"
AMT Liability ($b),40.1,42.3,44.7,47.0,49.5,52.1,55.1,58.2,61.3,64.4
AMT Filers (#m),5.0,5.2,5.3,5.5,5.6,5.8,6.0,6.2,6.4,6.6
Tax before Credits ($b),"1,563.1","1,640.0","1,706.0","1,766.3","1,831.9","1,909.0","1,993.4","2,085.3","2,183.9","2,288.9"
Refundable Credits ($b),218.8,218.3,218.6,218.5,219.4,219.5,219.7,220.1,220.2,219.8
Nonrefundable Credits ($b),72.7,74.1,74.9,75.3,76.2,77.1,78.0,79.4,80.9,82.4
Reform Surtaxes ($b),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Ind Income Tax ($b),"1,305.3","1,382.2","1,448.0","1,508.6","1,573.5","1,650.9","1,735.8","1,827.5","1,926.4","2,032.3"
Payroll Taxes ($b),"1,045.3","1,093.9","1,141.4","1,186.7","1,233.7","1,284.4","1,338.8","1,396.5","1,456.8","1,519.4"
Combined Liability ($b),"2,350.6","2,476.2","2,589.3","2,695.3","2,807.2","2,935.3","3,074.6","3,224.0","3,383.2","3,551.8"